name: ecbuild
on:
  push:
    tags:
      - v**
      - do**
      - fix**
      - tmp**
      - dev**
jobs:
  ecbuild:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker-compose -f docker/prod/docker-compose.yml build
