name: ecbuild
on:
  push:
    tags:
      - v**
      - do**
      - fix**
      - tmp**
      - dev**
jobs:
  ecbuild:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Build
      - run: echo "done"
      #   run: docker-compose -f docker/prod/docker-compose.yml build
      # - name: Discovery Docker Images
      #   run: docker image ls
      # - name: Login to Container Registry
      #   run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      # - name: Push App
      #   run: |
      #     docker tag system-app-prod:hot ghcr.io/learnkad/app && docker push ghcr.io/learnkad/app
      #     docker tag system-app-prod:hot ghcr.io/learnkad/app:$GITHUB_REF_NAME && docker push ghcr.io/learnkad/app:$GITHUB_REF_NAME     
      # - name: Push Proxy
      #   run: |
      #     docker tag system-proxy-prod:hot ghcr.io/learnkad/proxy && docker push ghcr.io/learnkad/proxy
      #     docker tag system-proxy-prod:hot ghcr.io/learnkad/proxy:$GITHUB_REF_NAME && docker push ghcr.io/learnkad/proxy:$GITHUB_REF_NAME
      # - name: Push Static
      #   run: |
      #     docker tag system-static-prod:hot ghcr.io/learnkad/static && docker push ghcr.io/learnkad/static
      #     docker tag system-static-prod:hot ghcr.io/learnkad/static:$GITHUB_REF_NAME && docker push ghcr.io/learnkad/static:$GITHUB_REF_NAME
